### ISSUE TITLE
Issue inside _forecastMoveUnit

### ISSUE THREAD

**Issue by bounty1342** [quire-io/scroll-to-index#69]
Hi,

In a GridView.builder I have the following issue :
```
I/flutter (19656): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (19656): 'package:scroll_to_index/scroll_to_index.dart': Failed assertion: line 382 pos 14: '() {
package:scroll_to_index/scroll_to_index.dart:1
I/flutter (19656):         if (position.extentAfter > 0)
I/flutter (19656):           return (offsetToLastState?.offset ?? 0) >= 0;
I/flutter (19656):         else
I/flutter (19656):           return true;
I/flutter (19656):       } ()': Please try to wrap all first level children widgets with AutoScrollTag.
I/flutter (19656): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (19656): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (19656): #2      AutoScrollControllerMixin._forecastMoveUnit
package:scroll_to_index/scroll_to_index.dart:382
I/flutter (19656): #3      AutoScrollControllerMixin._scrollToIndex
package:scroll_to_index/scroll_to_index.dart:271
I/flutter (19656): <asynchronous suspension>
I/flutter (19656): ----------------------------------------------------
```

I do have the key in an ascending order given by the itembuilder of the GridView:
```
AutoScrollTag(
              key: ValueKey<int>(index),
              controller: bookPagesController,
              index: index,
              child: _Page(
                index: index,
              ),
            );
```

When this happen the resulting scroll is really off (like double the reel index).
Try to setup suggestedRowHeight, but didn't change it.
```
      bookPagesController = AutoScrollController(
        suggestedRowHeight:
            100.vw / (100.vw * heightPageReelBook / widthPageReelBook + 75),
      );
```

Regards

**Comment by jerrywell** [comment]
the given code blocks look fine for this package. can you provide the minimal sample to reproduce it?

btw, please make sure that under the children of gridview, there shouldn't be any other widget type except `AutoScrollTag`.

**Comment by mzl1988** [comment]
The same problem occurs if multiple AutoScrollTags are very high

**Comment by jerrywell** [comment]
Solved by https://github.com/quire-io/scroll-to-index/commit/8e6714dbd6f83d937e8d3fb492ccbfd26d86a964
